### ISSUE TITLE
Wrong Contest Duration

### ISSUE THREAD

**Issue by arnoob16** [arnoob16/cpAPI#3]
# Issue
Contests with a duration of less than 1 hour show `0 Days` as the `contestDuration` parameter.

# How it should look like
The `contestDuration` parameter should show the exact duration of the contest, which in this case is 45 minutes.

# Screenshot
![image](https://user-images.githubusercontent.com/49037005/106706006-f7efd080-6614-11eb-9e41-8b5c6534cf94.png)

**Comment by Sumit112192** [comment]
This issue is happening only with codechef competitons or for all?

**Comment by arnoob16** [comment]
Currently only CodeChef has listed a competition of time less than an hour. So can't say if it will happen with others or not.

**Comment by Sumit112192** [comment]
I have solved the codechef issue. Check that out
